### ISSUE TITLE
API issue - user should drop txt file containing commands one per line to jobs folder

### ISSUE THREAD

**Issue by michaeltschreiber** [jjrobertson14/ParallelBashJobsEngine#1]

**Comment by jjrobertson14** [comment]
[Brainstorming]

How to resolve having 3 different ways of running jobs:

    - 1) (currently works) run script as job
    - 2) (currently works) run script and each line of output from script (that are marked as commands with _-_-_COMMAND prefix) 
    - 3) (this issue) drop txt file containing commands one per line

So (1) and (2) work at the same time, only need to configure a different way to have (3) work.

- Filename Pattern?
- Configuration file
- Different Directory (!)

**Comment by jjrobertson14** [comment]
[Re: Different Directory Approach]

Directory name candidates:
- [run each line as command] 
    - command-list-jobqueue / run-each-line-as-job-jobqueue / jobqueue
- [run each line of standard out as command] 
    - run-standard-out-as-commands-jobqueue / run-standard-out-as-jobs-jobqueue

**Comment by jjrobertson14** [comment]
[STEPS] 
- [x] Decide method 
    - Different Directory and configuration option to activate either/or directory
- [x] Name the 2 different directories
    1. run-each-line-as-job-jobqueue
    2. run-standard-out-as-jobs-jobqueue
- [x] Copy content of parallelWithEchoedJobCommands.sh to parallelJobEngine.sh
- [x] Rename references of "jobqueue-for-jobs-that-echo-commands" dir to "run-standard-out-as-jobs-jobqueue"
    - [x] Add references to new dir run-each-line-as-job-jobqueue in similar locations
- [x] Implement "drop txt file containing commands one per line"
    - Just follow the TODOs
- [x] Update README to have separate sections for trying example with parallelWithEchoedJobCommands.sh and for using parallelJobEngine
- [x] Create pbjengined.conf, and add setting to set JOB FILE type to use (default to run each line as job)
- [x] Update init script to copy pbjengined.conf config file to /etc/pbjengined.conf
- [x] Update README (to describe /etc/pbjengined.conf)
- [ ] commit Docker image
