### ISSUE TITLE
Number of simultaneous jobs should be an argument to parallelJobEngine.sh

### ISSUE THREAD

**Issue by michaeltschreiber** [jjrobertson14/ParallelBashJobsEngine#2]

**Comment by michaeltschreiber** [comment]
If no argument is supplied, read ENV:NUMBER_OF_CORES for default value of simultaneous jobs

**Comment by jjrobertson14** [comment]
[CLARIFICATION]

There are actually 2 core counts:

1. Count of cores used to process each job file itself
2. Count of cores used to process each command from the job file with multiple cores (be it echoed to standard out or run as an individual job command when each line is meant to be run with multiple cores)

**Comment by jjrobertson14** [comment]
Steps

- [x] name each of the two core count parameters
- [x] Implement core count  (1) (process job file) 
    - Perhaps default to 2?

- [x] Implement core count (2) (run job commands on multiple cores)
- [x] Implement reading ENV:NUMBER_OF_CORES as default for count (2) (run job commands on multiple cores), also implement default count (1)

**Comment by jjrobertson14** [comment]
Get core count with CORE_COUNT=$(getconf _NPROCESSORS_ONLN).

getconf is pretty ancient. 
https://en.wikipedia.org/wiki/List_of_Unix_commands does not list on what system it first appeared.
