### ISSUE TITLE
Add bootstrap script that will install jobs engine as a daemon/service (jobsEngineD)

### ISSUE THREAD

**Issue by michaeltschreiber** [jjrobertson14/ParallelBashJobsEngine#3]

**Comment by jjrobertson14** [comment]
[Enhancement]
- Also have it curl/install parallel?

**Comment by jjrobertson14** [comment]
Steps:

- [x] Research how to install script as daemon/service (jobsEngineD)
- [x] Create initd script for daemon (pbjengined_ubuntu)
- [x] (nevermind, upstart is no longer supported) Create Upstart service file (pbengine_service_ubuntu)
- [x] create bootstrap script
- [x] enhance bootstrap script: curl/install parallel if not installed to job script
- [x] update README

**Comment by jjrobertson14** [comment]
[Helpful Article]
https://www.linux.com/training-tutorials/managing-linux-daemons-init-scripts/

**Comment by jjrobertson14** [comment]
On creating an init.d service for Ubuntu:

https://askubuntu.com/questions/1261213/how-to-write-an-init-script-that-will-execute-an-existing-start-script-in-ubuntu
https://www.thegeekstuff.com/2012/03/lsbinit-script/
